#!/usr/bin/env bash
set -euo pipefail

# Build all Java sources and run the compiler on a provided test file,
# then disassemble and execute the generated bytecode.
#
# Usage:
#   ./make.sh                       # uses testfiles/Compilertest.pl0
#   ./make.sh testfiles/good_minimal.pl0

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$ROOT_DIR/src"
COMPILED_DIR="$ROOT_DIR/compiled"
DEFAULT_TEST_FILE="$ROOT_DIR/compiled/Compilertest.pl0"
TEST_FILE="${1:-$DEFAULT_TEST_FILE}"
OUT_CL0="$COMPILED_DIR/out.cl0"

cd "$ROOT_DIR"

mkdir -p "$COMPILED_DIR"
#if file out.cl0 exists, remove
if [[ -f "$OUT_CL0" ]]; then
  echo "for cleaner runs, removing existing output file: $OUT_CL0"
  rm -f "$OUT_CL0"
fi


echo "[1/4] Compiling Java sources..."
# Compile into src/ so 'java -cp src' can load classes reliably.
javac -d "$SRC_DIR" $(find "$SRC_DIR" -name '*.java' ! -path '*/AST/*')

echo "[2/4] Running PL/0 compiler on: $TEST_FILE"
#java -cp "$SRC_DIR" Compiler.Compiler "$TEST_FILE"
java -cp "$SRC_DIR" Compiler.GUI "$TEST_FILE"
if [[ ! -f "$OUT_CL0" ]]; then
  echo "ERROR: Expected output bytecode file not found: $OUT_CL0" >&2
  exit 1
fi

echo "[3/4] Running VM tools on: $OUT_CL0"
if [[ -x "$COMPILED_DIR/outCl0" ]]; then
(cd "$COMPILED_DIR" && ./outCl0 out.cl0) || \
echo "WARN: outCl0 failed, continuing anyway." >&2
else
  echo "WARN: $COMPILED_DIR/outCl0 not found or not executable; skipping disassembly." >&2
fi

echo "[4/4] Executing generated bytecode on r2432 VM:"
if [[ -x "$COMPILED_DIR/r2432" ]]; then
  (cd "$COMPILED_DIR" && ./r2432 out.cl0)
else
  echo "WARN: $COMPILED_DIR/r2432 not found or not executable; skipping execution." >&2
fi
