package Compiler;

import Lexer.*;
import Parser.Parser;
import SymbolTable.*;
import TestPrinter.ASTPrinter;
import Types.Program;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

public class Compiler {
    static boolean hadError = false;
    static boolean hadRuntimeError = false;
    static String File = "";


    public static void main(String[] args) throws IOException {

        // If too many arguments were passed, we print the usage
        if (args.length > 1) {
            System.out.println("Usage: pl0 [script]");
            System.exit(64);
        }
        // If file was passed we start the runFile function
        else if (args.length == 1) {
            File = args[0];
            runFile(args[0]);
        }
        else{
            runPrompt();
        }

        // In the future we could extend runPrompt to be more REPL-like,
        // but for now we just reset hadError after each line.
    }

    public static String getFile() {
        return File;
    }

    // If file was passed, we call this function
    private static void runFile(String Path) throws IOException {
        byte[] filedata = Files.readAllBytes(Paths.get(Path));
        run(new String(filedata));
        if (hadError) System.exit(65); // if there was an error, exit with code 65
        if (hadRuntimeError) System.exit(70);
    }

    private static void runPrompt() throws IOException {
        InputStreamReader input = new InputStreamReader(System.in);
        BufferedReader reader = new BufferedReader(input);

        for (;;) {
            System.out.print("> ");
            String line = reader.readLine();
            if (line == null) break;
            run(line);
            hadError = false;
        }
    }

    /**
     * Pipeline im aktuellen Stand:
     *   source -> Lexer -> Tokens -> Parser -> AST -> Resolver (Symboltabelle/Semantik)
     */
    private static void run(String source) {
        System.out.println("\n-------------------------------------------------");
        System.out.println("\nSource Code:\n");
        System.out.println(source);

        Lexer lexer = new Lexer(source);
        List<Token> tokens = lexer.lexSomeTokens();
        System.out.println("\n-------------------------------------------------\n");
        System.out.println("Tokens:\n");
        for (Token token : tokens) {
            System.out.println(token);
        }
        System.out.println("\n-------------------------------------------------");

        Parser parser = new Parser(tokens);
        Program program = parser.parseProgram();
        if (hadError || program == null){
            System.out.println("Parse NOT OK!\n");
            return;
        }

        System.out.println("Parse OK!\n");


        try {
            SymbolTable symbols = new SymbolTable();
            SemanticTraveler sem = new SemanticTraveler(symbols);
            DataBunker bunker = sem.analyze(program);
            System.out.println("Semantic analysis OK!\n");
            System.out.println("Bunker informations:\n");
            System.out.println(bunker.debugDump());
            CodeGenerator generator = new CodeGenerator();
            byte[] bytecode = generator.generate(program, bunker);
            System.out.println("\nGenerated bytecode (hex):\n");
            for (byte b : bytecode) {
                System.out.printf("%02X ", b);
            }
            writeBytesInFile(bytecode);

        } catch (RuntimeException ex) {
            System.out.println("Semantic analysis NOT OK!\n");
            System.err.println(ex.getMessage()); // rudimentary EN ok
            return;
        }

        System.out.println("\nAST:\n");
        System.out.println(new ASTPrinter().print(program));
    }

    private static void writeBytesInFile(byte[] bytecode) {
        File f = new File("compiled/out.cl0");

        try(FileOutputStream fos = new FileOutputStream(f))
        {
            fos.write(bytecode);
        }
        catch (IOException e)
        {
            System.err.println("Failed to write bytecode to file: " + e.getMessage());
        }
    }

    public static void error(int line, String message) {
        report(line, "", message);
    }

    public static void report(int line, String where, String message) {
        System.err.println("[line " + line + "] Error" + where + ": " + message);
        hadError = true;
    }

    public static void error(Token token, String message) {
        if (token.type == TokenType.EOF) {
            report(token.line, " at end", message);
        } else {
            report(token.line, " at '" + token.lexeme + "'", message);
        }
    }

    static void runtimeError(RuntimeError error)
    {
        System.err.println(error.getMessage() + "\n[line " + error.token.line + "]");
        hadRuntimeError = true;
    }

}